<script type="text/javascript" src="<?=base_url('/assets/js/vendor/jquery-ui.min.js')?>"></script>
<script type="text/javascript" src="<?=base_url('/assets/js/vendor/jquery.ui.touch-punch.min.js')?>"></script>
<script type="text/javascript" src="<?=base_url('/assets/js/vendor/jquery.panzoom.min.js')?>"></script>
<script type="text/javascript" src="<?=base_url('/assets/js/vendor/rgbcolor.js')?>"></script>
<script type="text/javascript" src="<?=base_url('/assets/js/vendor/canvg.js')?>"></script>
<script type="text/javascript" src="<?=base_url('/assets/js/models/transit.js')?>"></script>
<script type="text/javascript" src="<?=base_url('/assets/js/collections/transits.js')?>"></script>
<script type="text/javascript" src="<?=base_url('/assets/js/views/transit.add.js')?>"></script>
<script type="text/javascript" src="<?=base_url('/assets/js/views/transit.show.js')?>"></script>